version: 2.1

jobs:
  clippy:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo clippy
  
  build:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo test
